Class {
	#name : #ODBTestClass1,
	#superclass : #Object,
	#instVars : [
		'one',
		'two',
		'three'
	],
	#category : #'OmniBase-Tests'
}

{ #category : #accessing }
ODBTestClass1 >> one [

	^ one
]

{ #category : #accessing }
ODBTestClass1 >> one: anObject [

	one := anObject
]

{ #category : #accessing }
ODBTestClass1 >> three [

	^ three
]

{ #category : #accessing }
ODBTestClass1 >> three: anObject [

	three := anObject
]

{ #category : #accessing }
ODBTestClass1 >> two [

	^ two
]

{ #category : #accessing }
ODBTestClass1 >> two: anObject [

	two := anObject
]
